### ISSUE TITLE
ReSpec build is stuk door invalid JavaScript

### ISSUE THREAD

**Issue by ehotting** [Logius-standaarden/publicatie#3]
Zie https://github.com/Logius-standaarden/publicatie/pull/2#pullrequestreview-1948519685

**Comment by ehotting** [comment]
Wellicht goed om het mergen van PR's die de build stuk maken af te vangen?

**Comment by ehotting** [comment]
@hugoboos Dank voor de fix!

**Comment by sanderke** [comment]
Excuses. Dit had inderdaad afgevangen moeten worden. De wijziging staat vannacht op logius.nl of er kan nu verwezen worden naar deze locatie:

https://logius-standaarden.github.io/publicatie/respec/organisation-config.js
